services:
  - type: web
    name: Mopgomyouth
    env: node
    plan: starter
    region: oregon
    # Optimized for real-time features
    autoDeploy: true
    previewsEnabled: false
    healthCheckPath: /api/health
    buildCommand: NODE_OPTIONS="--max-old-space-size=1024" npm ci && npx prisma generate && npx tsx scripts/create-super-admin.ts && npx tsx scripts/seed-settings.ts && NODE_OPTIONS="--max-old-space-size=1024" npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: PRISMA_GENERATE_SKIP_AUTOINSTALL
        value: true
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: NEXTAUTH_URL
        value: https://youth-registration-system.onrender.com
      - key: NEXTAUTH_SECRET
        value: your-super-secure-nextauth-secret-change-this-in-production
      - key: SKIP_ENV_VALIDATION
        value: false
      - key: REAL_TIME_STATS
        value: true
      - key: STAFF_REALTIME_ACCESS
        value: true
      - key: BRANCH_SELECTION_REQUIRED
        value: true
      - key: ANALYTICS_ENABLED
        value: true
      - key: SYSTEM_NAME
        value: Mopgomyouth
      - key: ORGANIZATION_NAME
        value: Mopgomglobal
      - key: SUPPORT_EMAIL
        value: admin@mopgomglobal.com
      - key: DEFAULT_ADMIN_EMAIL
        value: admin@mopgomglobal.com
      - key: DEFAULT_ADMIN_PASSWORD
        value: Admin123!
      - key: MINIMUM_AGE
        value: 13
      - key: REGISTRATION_OPEN
        value: true
      - key: ENABLE_SMS_NOTIFICATIONS
        value: false
      - key: ENABLE_EMAIL_NOTIFICATIONS
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: mopgomyouth-db
          property: connectionString

databases:
  - name: mopgomyouth-db
    databaseName: mopgomyouth
    user: mopgomyouth
    plan: free
